services:
  - type: web
    name: devflow
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile.standalone
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SQL_INIT_MODE
        value: always
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: JAVA_OPTS
        value: "-Xmx160m -Xms48m -XX:+UseSerialGC -XX:MaxMetaspaceSize=64m -XX:ReservedCodeCacheSize=32m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
