server:
  port: 8080

spring:
  application:
    name: DevFlow
  datasource:
    url: jdbc:mysql://localhost:3306/productionplatform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.example.productionplatform.admin.model
  configuration:
    map-underscore-to-camel-case: true
